version: '3'
services:
  db:
    image: mysql
    container_name: 'django_mysql'
    hostname: 'django_mysql'
    environment:
      MYSQL_DATABASE: 'djangodocker_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
  nginx:
    image: nginx
    container_name: 'django_nginx'
    hostname: 'django_nginx'
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/djangodocker/static
    ports:
      - 80:80
    
